### ISSUE TITLE
Workflow test падает потому что проект на .net7

### ISSUE THREAD

**Issue by iigaz** [sOlnblshkO/HT.ITIS-3.1-student#7]
Предлагаемое исправление: скопировать Setup dotnet v7.0.x из build в test

**Comment by s1ches** [comment]
Для ускорения решения вопроса, заменить workflow на это:

```
name: .NET

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build in Debug mode
        run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Build in Debug mode
        run: dotnet build
      - name: Tests
        run: dotnet test --no-build
        working-directory: Dotnet.Homeworks.Tests
```
